// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1pHd0Ek_TWoynzck4Xdiaae1TM57Pp0',
    appId: '1:251517436194:android:f1a6e90ebee897dbff257b',
    messagingSenderId: '251517436194',
    projectId: 'irish-driving-test-app-v1',
    storageBucket: 'irish-driving-test-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMbzHWN_Gfj8gWPqIIZcXpa9wYJ6n-bU',
    appId: '1:251517436194:ios:ea57210bd7aee1f0ff257b',
    messagingSenderId: '251517436194',
    projectId: 'irish-driving-test-app-v1',
    storageBucket: 'irish-driving-test-app-v1.firebasestorage.app',
    iosBundleId: 'com.antigravity.irishdrivingtest.irishDrivingTest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTBoi5ryWzMXRjIm5QMUmPTKYuUSYgXk',
    appId: '1:251517436194:web:d474a3798e140228ff257b',
    messagingSenderId: '251517436194',
    projectId: 'irish-driving-test-app-v1',
    authDomain: 'irish-driving-test-app-v1.firebaseapp.com',
    storageBucket: 'irish-driving-test-app-v1.firebasestorage.app',
  );

}