import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_remote_config/firebase_remote_config.dart';
import 'firebase_options.dart'; // This file is generated by `flutterfire configure`
import 'providers/quiz_provider.dart';
import 'providers/user_provider.dart';
import 'screens/home_screen.dart';
import 'screens/revision_screen.dart';

import 'services/analytics_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Initialize Crashlytics (Not supported on Web)
  if (!kIsWeb) {
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  }
  
  // Initialize Remote Config for A/B testing
  final remoteConfig = FirebaseRemoteConfig.instance;
  await remoteConfig.setConfigSettings(RemoteConfigSettings(
    fetchTimeout: const Duration(minutes: 1),
    minimumFetchInterval: const Duration(hours: 1),
  ));
  await remoteConfig.setDefaults(const {
    "show_tooltips": true,
    "quiz_timer_minutes": 45,
  });
  await remoteConfig.fetchAndActivate();
  
  runApp(const IrishDrivingTestApp());
}

class IrishDrivingTestApp extends StatelessWidget {
  final List<NavigatorObserver>? navigatorObservers; // Allow injection for testing

  const IrishDrivingTestApp({
    super.key,
    this.navigatorObservers,
  });

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => QuizProvider()),
      ],
      child: MaterialApp(
        title: 'Irish Driving Test',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          useMaterial3: true,
          primaryColor: const Color(0xFF2E7D32), // Emerald Green
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFF2E7D32),
            primary: const Color(0xFF2E7D32),
            secondary: const Color(0xFF81C784),
            surface: Colors.grey[50]!,
          ),
          textTheme: GoogleFonts.poppinsTextTheme(
            Theme.of(context).textTheme,
          ),
          appBarTheme: const AppBarTheme(
            surfaceTintColor: Colors.transparent,
          ),
        ),
        navigatorObservers: navigatorObservers ?? [
          AnalyticsService().getAnalyticsObserver(),
        ],
        home: const HomeScreen(),
        routes: {
          '/revision': (context) => const RevisionScreen(),
        },
      ),
    );
  }
}
